// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9d9YPGMZrPhAtCj3PPtPSnVyOuIN-s8E',
    appId: '1:219675563964:web:9a418d70bead1a13a67db9',
    messagingSenderId: '219675563964',
    projectId: 'roomies-a4d00',
    authDomain: 'roomies-a4d00.firebaseapp.com',
    storageBucket: 'roomies-a4d00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM6TMRaDVaVwii3NK_2OINkyr-as6FGMo',
    appId: '1:219675563964:android:88592e62cc5262bfa67db9',
    messagingSenderId: '219675563964',
    projectId: 'roomies-a4d00',
    storageBucket: 'roomies-a4d00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm_6aCFA5Ab-oOOA4QqMbxQ03kb-sekg0',
    appId: '1:219675563964:ios:1f861f8f36c2c6fca67db9',
    messagingSenderId: '219675563964',
    projectId: 'roomies-a4d00',
    storageBucket: 'roomies-a4d00.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm_6aCFA5Ab-oOOA4QqMbxQ03kb-sekg0',
    appId: '1:219675563964:ios:1f861f8f36c2c6fca67db9',
    messagingSenderId: '219675563964',
    projectId: 'roomies-a4d00',
    storageBucket: 'roomies-a4d00.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9d9YPGMZrPhAtCj3PPtPSnVyOuIN-s8E',
    appId: '1:219675563964:web:1495727fe0d5b142a67db9',
    messagingSenderId: '219675563964',
    projectId: 'roomies-a4d00',
    authDomain: 'roomies-a4d00.firebaseapp.com',
    storageBucket: 'roomies-a4d00.appspot.com',
  );

}